heat_template_version: 2013-05-23
description: > 
  heat --debug stack-create -f floatingip-create.yaml -P public_net_id=3ba20b53-b1bb-4425-90a3-be524c1a7fe5 floatingip02
 
parameters:
  public_net_id:
    type: string
    description: extranal network id
 
resources:
   floatingip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
 
