heat_template_version: 2013-05-23
description: >
  heat --debug stack-create -f multi-floatingip.yaml -P num_floatingips=2 -P public_net_id=3ba20b53-b1bb-4425-90a3-be524c1a7fe5 floatingip
 
parameters:
  num_floatingips:
    type: number
    description: number of flatingip
    default: 1
    constraints:
      - range: { min: 1, max: 100 }
 
  public_net_id:
    type: string
    description: extranal network id
 
resources:
#  floatingip:
#   type: OS::Neutron::FloatingIP
#   properties:
#     floating_network_id: { get_param: public_net_id }
#     description: Floatingip for stack
 
 
  group_of_floatingips:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: num_floatingips }
      resource_def:
        type: OS::Neutron::FloatingIP
        properties:
          floating_network_id: { get_param: public_net_id }
#        type: { get_resource: floatingip }


