heat_template_version: 2013-05-23
description: >
  heat --debug stack-create -f resourceGroup.yaml -P num_resources=2 -P public_net_id=3ba20b53-b1bb-4425-90a3-be524c1a7fe5 floatingip02
 
parameters:
  num_resources:
    type: number
    description: number of resources
    default: 1
    constraints:
      - range: { min: 1, max: 100 }

  public_net_id:
    type: string
    description: extranal network id
 
resources:
  group_of_resources:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: num_resources }
      resource_def:
        type: floatingip-create.yaml
        properties:
          public_net_id: { get_param: public_net_id } 


