heat_template_version: 2013-05-23

description: >
  HOT template to deploy instantiate an instance with a minimum working network, the pre-configured items are:
  1. Net
  2. Subnet (ip: 192.168.1.0/24)
  3. Router
  4. RouterInterface
  5. SecurityGroup
  6. Floating IP
 
parameters:
  public_net:
    type: string
    label: public network name
    description: network to attach instance to

resources:
  private_net:
    type: OS::Neutron::Net
    properties:
      name: default-net
 
  private_subnet:
    type: OS::Neutron::Subnet
    depends_on: private_net
    properties:
      network_id: { get_resource: private_net }
      name: default-subnet
      cidr: 192.168.1.0/24
      gateway_ip: 192.168.1.1
  
  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net}

  router1:
    type: OS::Neutron::Router
    properties:
      name: default_router
      external_gateway_info:
          network: { get_param : public_net }

  router1_interface:
    type: OS::Neutron::RouterInterface
    depends_on: [ router1,private_net,private_subnet ]
    properties:
      router_id: { get_resource : router1 }
      subnet_id: { get_resource : private_subnet }

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Slight change to the default security group
      name: defult_security_group
      rules: [
        {
          "remote_ip_prefix": 0.0.0.0/0,
          "protocol": icmp,
          "direction": "ingress",
          "ethertype": "IPv4"
        },
        {
          "remote_ip_prefix": 0.0.0.0/0,
          "protocol": icmp,
          "direction": "egress",
          "ethertype": "IPv4"
        },
        {
          "remote_ip_prefix": 0.0.0.0/0,
          "protocol": tcp,
          "port_range_min": 22,
          "port_range_max": 22,
          "direction": "ingress",
          "ethertype": "IPv4"
        },
        {
          "remote_ip_prefix": 0.0.0.0/0,
          "protocol": tcp,
          "port_range_min": 22,
          "port_range_max": 22,
          "direction": "egress",
          "ethertype": "IPv4"
        },
        {
          "remote_ip_prefix": 0.0.0.0/0,
          "protocol": tcp,
          "port_range_min": 80,
          "port_range_max": 80,
          "direction": "ingress",
          "ethertype": "IPv4",
        },
        {
          "remote_ip_prefix": 0.0.0.0/0,
          "protocol": tcp,
          "port_range_min": 80,
          "port_range_max": 80,
          "direction": "egress",
          "ethertype": "IPv4",
        },
        {
          "remote_ip_prefix": 0.0.0.0/0,
          "protocol": tcp,
          "port_range_min": 443,
          "port_range_max": 443,
          "direction": "ingress",
          "ethertype": "IPv4"
        },
        {
          "remote_ip_prefix": 0.0.0.0/0,
          "protocol": tcp,
          "port_range_min": 443,
          "port_range_max": 443,
          "direction": "egress",
          "ethertype": "IPv4"
        }
      ]

 
